import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { generateTextEmbedding } from "@/lib/ai";
import { GoogleGenerativeAI } from "@google/generative-ai";

const apiKey = process.env.GEMINI_API_KEY;
let aiClient: any = null;
if (apiKey) {
  try {
    aiClient = new GoogleGenerativeAI(apiKey);
  } catch (e) {
    console.error("Failed to init AI client for Ask route:", e);
  }
}

function cosineSimilarity(vecA: number[], vecB: number[]): number {
  let dotProduct = 0.0;
  let normA = 0.0;
  let normB = 0.0;
  const length = Math.min(vecA.length, vecB.length);
  for (let i = 0; i < length; i++) {
    dotProduct += vecA[i] * vecB[i];
    normA += vecA[i] * vecA[i];
    normB += vecB[i] * vecB[i];
  }
  if (normA === 0 || normB === 0) return 0;
  return dotProduct / (Math.sqrt(normA) * Math.sqrt(normB));
}

export async function POST(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    if (!session || !session.user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const workspaceId = (session.user as any).workspaceId;
    const body = await req.json();
    const { query } = body;

    if (!query || typeof query !== "string" || query.trim().length === 0) {
      return NextResponse.json({ error: "Query is required" }, { status: 400 });
    }

    // 1. Generate Query Vector
    const queryVector = await generateTextEmbedding(query);

    // 2. Fetch all feedback embeddings for workspace
    const embeddings = await prisma.embedding.findMany({
      where: {
        feedback: {
          workspaceId,
        },
      },
      include: {
        feedback: true,
      },
    });

    if (embeddings.length === 0) {
      return NextResponse.json({
        answer: "There are no customer feedbacks in your workspace to answer this question. Please upload or ingest some feedback first!",
        citations: [],
      });
    }

    // 3. Compute cosine similarity
    const matches = embeddings
      .map((emb) => {
        try {
          const vectorArray = JSON.parse(emb.vector) as number[];
          const similarity = cosineSimilarity(queryVector, vectorArray);
          return {
            feedback: emb.feedback,
            similarity,
          };
        } catch (e) {
          return {
            feedback: emb.feedback,
            similarity: 0,
          };
        }
      })
      .filter((m) => m.similarity > 0.1) // Minimum match threshold
      .sort((a, b) => b.similarity - a.similarity)
      .slice(0, 5); // Take top 5

    if (matches.length === 0) {
      return NextResponse.json({
        answer: "No relevant customer feedback was found matching your query. Try asking something else or broadening your question.",
        citations: [],
      });
    }

    // 4. Ask Gemini or run local fallback answer
    const contextText = matches
      .map(
        (m) =>
          `[ID: ${m.feedback.id}] (Title: ${m.feedback.title}) - Description: ${m.feedback.description}`
      )
      .join("\n\n");

    let answer = "";
    if (aiClient) {
      try {
        const model = aiClient.getGenerativeModel({ model: "gemini-2.5-flash" });
        const prompt = `
          You are Ask LOOP, an AI product assistant. Answer the user's question about customer feedback based ONLY on the provided feedbacks. 
          Cite references to feedbacks by their exact ID inside brackets, e.g. [cuid-xxxx].
          Be concise and objective. If the feedback context does not contain the answer, say "Based on the feedback in the workspace, I cannot answer this query."
          
          User Question: "${query}"

          Context Feedbacks:
          ${contextText}
        `;

        const response = await model.generateContent({ contents: [{ parts: [{ text: prompt }] }] });
        answer = response.text || "No response generated by AI.";
      } catch (err) {
        console.error("Gemini RAG failed:", err);
      }
    }

    // Fallback answer generator if Gemini was missing or failed
    if (!answer) {
      const positiveCount = matches.filter(m => (m.feedback.rating || 0) >= 4).length;
      const negativeCount = matches.filter(m => (m.feedback.rating || 0) <= 2).length;
      answer = `[Local Engine] Found ${matches.length} matching feedback records. The matched feedback set contains ${positiveCount} positive and ${negativeCount} critical entries. Typical issues relate to feature requests and system usage. Here are the top citations: ${matches.map(m => `[${m.feedback.id}]`).join(", ")}.`;
    }

    const citations = matches.map((m) => ({
      id: m.feedback.id,
      title: m.feedback.title,
      description: m.feedback.description,
      sentiment: m.feedback.sentiment || "NEU",
      rating: m.feedback.rating,
      similarity: parseFloat(m.similarity.toFixed(3)),
    }));

    return NextResponse.json({
      answer,
      citations,
    });
  } catch (error) {
    console.error("Ask Loop API error:", error);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
